/*! \file test_read_restart.cpp
 *
 * ### Unit test for ../src/io/read_restart.cpp
 *
 * The function under test is:
 *
 *     void read_restart(long long int& simItr, std::ifstream& restartFile,
 *                       Parameters& params, SimulVolume& simulVolume,
 *                       std::vector<Molecule>& moleculeList,
 *                       std::vector<Complex>& complexList,
 *                       std::vector<MolTemplate>& molTemplateList,
 *                       std::vector<ForwardRxn>& forwardRxns,
 *                       std::vector<BackRxn>& backRxns,
 *                       std::vector<CreateDestructRxn>& createDestructRxns,
 *                       std::vector<TransmissionRxn>& transmissionRxns,
 *                       std::map<std::string, int>& observablesList,
 *                       Membrane& membraneObject, copyCounters& counterArrays)
 *
 * It is a large, strictly positional text parser: every field of the restart
 * file must appear in exactly the order in which the routine consumes it.  The
 * strategy used here is therefore:
 *
 *   1. Synthesise a *minimal but complete* restart file whose layout matches the
 *      read order of the parser exactly (1 molecule template, 1 forward + 1 back
 *      reaction, 2 molecules, 2 complexes, 1 observable, counter arrays).
 *   2. Call read_restart() once on that file.
 *   3. Assert, section by section, that every value landed in the right member.
 *
 * Important notes about the code under test that shaped this test:
 *
 *   - read_restart() reads into several *static* members (MolTemplate::numMolTypes,
 *     MolTemplate::numEachMolType, MolTemplate::absToRelIface,
 *     Interface::State::totalNumOfStates, RxnBase::numberOfRxns,
 *     RxnBase::totRxnSpecies, Molecule::numberOfMolecules, Molecule::emptyMolList,
 *     Complex::numberOfComplexes, Complex::emptyComList and
 *     Parameters::lastUpdateTransition).  Those are shared with the whole test
 *     binary, so we snapshot them, clear them, run the parse, capture the parsed
 *     values, and then put the originals back.  All assertions are made against
 *     the captured copies.
 *   - The counterArrays event histograms are indexed *without* being resized
 *     (`counterArrays.events3D[i]`), so the caller is required to have sized them
 *     beforehand.  We pre-size them to the default eventArraySize (20), which is
 *     also the value written into the test file.
 *   - The SimulVolume block of the restart file is commented out in the source,
 *     so simulVolume must come back untouched - that is asserted too.
 *   - The parser calls exit(1) on a malformed reaction type and can throw from
 *     std::stod on a malformed angle field.  Neither path is exercised, because
 *     that would tear down the entire gtest binary.
 */

#include "io/io.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <map>
#include <string>
#include <vector>

namespace {

// -----------------------------------------------------------------------------
// Name of the scratch restart file created (and removed) by this test.
// -----------------------------------------------------------------------------
const char* const kRRFileName = "test_read_restart_generated.restart";

// Number of entries in the event histograms (matches copyCounters default).
const int kRREventArraySize = 20;

// -----------------------------------------------------------------------------
// The synthetic restart file.  Every line is positionally significant; see the
// inline commentary in rr_describe_layout() below for the mapping.
// -----------------------------------------------------------------------------
const char* const kRRFileContents =
    R"RESTART(#Restart file generated by the read_restart unit test
nItr = 1000
simItr = 250
timeRestartFrom = 0.005
numMolTypes = 1
numTotalSpecies = 3
numTotalComplex = 2
numTotalUnits = 4
numLipids = 0
timeStep = 0.1
max2DRxns = 5000
waterBox = 100 200 300
membraneInfo = -1 1 2 10 20 3000.5
freeLipidsEachState = 5 6
boundaryInfo = 0 0 1 0 0.0 0 0.0
overlapSepLimit = 0.25
rMaxLimit = 12.5
timeWrite = 10
trajWrite = 20
restartWrite = 30
pdbWrite = 40
assocDissocWrite = 1
checkPoint = 50
scaleMaxDisplace = 55.5
transitionWrite = 60
clusterOverlapCheck = 1
RNGwrite = 1
bondedComplexWrite = 70
3 1 2 3
#MolTemplates
1 1
1 0
1
0 A
5 100.5 2.5
0 0 0 0 1 0 500 0 0 0 -1
0.0 0.0 0.0
10.0 10.0 10.0
0.5 0.5 0.5
0
0
1
0 a
1.0 0.0 0.0
1
0 U
0
1 0
0
0
0
0
#Reactions
2 1 1 0 0 3
0 0 rxnA
1 0 1 0
0 A(a!1).A(a!1)
1 0 0 1.1 1.0 -1 -1
1.5 1.5708 3.14159 nan nan nan
0 0 1
0 0 1
0
0
2 0 0
1 2
2
0
a 0 0
X 0
0
a 0 0
X 0
2
0
a 2 0
Y 1
0
a 2 0
Y 1
1
10.5
0
1 0
1 0 1 0
0
0
0
1 2
2 0 0
2
0
a 2 0
Y 1
0
a 2 0
Y 1
2
0
a 0 0
X 0
0
a 0 0
X 0
1
0.5
0
#Molecules
2 2
0 0 0 0 5
100.5 0 0 0 0 0
1.0 2.0 3.0
1 0
0
0
1
0 0 0 0 U 0
1.5 2.0 3.0
0
0
0
0
0
0
1 0 1 0 6
100.5 0 0 1 0 0
-1.0 -2.0 -3.0
0
1 0
1 0
1
0 0 0 0 U 1
-1.5 -2.0 -3.0
0 0 0
0
0
0
0
0
0
0
#Complexes
2 2
0 0 2.5 100.5
0 0 0
0
1.0 2.0 3.0
10.0 10.0 10.0
0.5 0.5 0.5
1 0
1 1
1 0
1 0 3.5 100.5
1 0 1
0
-1.0 -2.0 -3.0
1.0 1.0 0.0
0.1 0.1 0.0
1 1
1 1
1 0
0
#Observables
1
obsA 7
#CounterArrays
3 1 2 4 5 6 7 8 20
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
#Species
2
1
0
2
1 3
)RESTART";

// -----------------------------------------------------------------------------
// Everything read_restart() produced, including copies of the static members it
// writes into.  All assertions look at this snapshot.
// -----------------------------------------------------------------------------
struct RRResult {
    bool fileOpened { false };

    long long int simItr { -1 };
    Parameters params {};
    SimulVolume simulVolume {};
    std::vector<Molecule> moleculeList {};
    std::vector<Complex> complexList {};
    std::vector<MolTemplate> molTemplateList {};
    std::vector<ForwardRxn> forwardRxns {};
    std::vector<BackRxn> backRxns {};
    std::vector<CreateDestructRxn> createDestructRxns {};
    std::vector<TransmissionRxn> transmissionRxns {};
    std::map<std::string, int> observablesList {};
    Membrane membraneObject {};
    copyCounters counterArrays {};

    // captured statics
    unsigned statNumMolTypes { 0 };
    std::vector<int> statNumEachMolType {};
    std::vector<int> statAbsToRelIface {};
    int statTotalNumOfStates { 0 };
    unsigned statNumberOfRxns { 0 };
    int statTotRxnSpecies { 0 };
    int statNumberOfMolecules { 0 };
    int statNumberOfComplexes { 0 };
    std::vector<int> statEmptyMolList {};
    std::vector<int> statEmptyComList {};
    std::vector<long long int> statLastUpdateTransition {};
};

/*! \brief Write the synthetic restart file, parse it, and capture the results.
 *
 * Static members touched by the parser are snapshotted / cleared / restored so
 * that no other test in the suite is affected by this one.
 */
RRResult rr_build_result()
{
    std::cerr << "\n[SETUP] test_read_restart.cpp\n"
              << "  Writing a synthetic restart file to \"" << kRRFileName << "\"\n"
              << "  and parsing it with read_restart() (src/io/read_restart.cpp).\n";

    // 1. Emit the file.
    {
        std::ofstream out(kRRFileName);
        out << kRRFileContents;
    }

    RRResult res;

    // 2. Pre-size the event histograms; read_restart() indexes them directly.
    res.counterArrays.events3D.assign(kRREventArraySize, 0);
    res.counterArrays.events3Dto2D.assign(kRREventArraySize, 0);
    res.counterArrays.events2D.assign(kRREventArraySize, 0);

    // 3. Snapshot every static the parser writes to, then clear the containers so
    //    the captured values reflect only what this file provided.
    const unsigned savedNumMolTypes = MolTemplate::numMolTypes;
    const std::vector<int> savedNumEachMolType = MolTemplate::numEachMolType;
    const std::vector<int> savedAbsToRelIface = MolTemplate::absToRelIface;
    const int savedTotalNumOfStates = Interface::State::totalNumOfStates;
    const unsigned savedNumberOfRxns = RxnBase::numberOfRxns;
    const int savedTotRxnSpecies = RxnBase::totRxnSpecies;
    const int savedNumberOfMolecules = Molecule::numberOfMolecules;
    const int savedNumberOfComplexes = Complex::numberOfComplexes;
    const std::vector<int> savedEmptyMolList = Molecule::emptyMolList;
    const std::vector<int> savedEmptyComList = Complex::emptyComList;
    const std::vector<long long int> savedLastUpdate = Parameters::lastUpdateTransition;

    MolTemplate::numEachMolType.clear();
    MolTemplate::absToRelIface.clear();
    Molecule::emptyMolList.clear();
    Complex::emptyComList.clear();
    Parameters::lastUpdateTransition.clear();

    // 4. Parse.
    {
        std::ifstream in(kRRFileName);
        res.fileOpened = in.is_open();
        if (res.fileOpened) {
            read_restart(res.simItr, in, res.params, res.simulVolume, res.moleculeList,
                res.complexList, res.molTemplateList, res.forwardRxns, res.backRxns,
                res.createDestructRxns, res.transmissionRxns, res.observablesList,
                res.membraneObject, res.counterArrays);
        }
    }

    // 5. Capture the statics as parsed.
    res.statNumMolTypes = MolTemplate::numMolTypes;
    res.statNumEachMolType = MolTemplate::numEachMolType;
    res.statAbsToRelIface = MolTemplate::absToRelIface;
    res.statTotalNumOfStates = Interface::State::totalNumOfStates;
    res.statNumberOfRxns = RxnBase::numberOfRxns;
    res.statTotRxnSpecies = RxnBase::totRxnSpecies;
    res.statNumberOfMolecules = Molecule::numberOfMolecules;
    res.statNumberOfComplexes = Complex::numberOfComplexes;
    res.statEmptyMolList = Molecule::emptyMolList;
    res.statEmptyComList = Complex::emptyComList;
    res.statLastUpdateTransition = Parameters::lastUpdateTransition;

    // 6. Restore the statics so the rest of the suite sees the original state.
    MolTemplate::numMolTypes = savedNumMolTypes;
    MolTemplate::numEachMolType = savedNumEachMolType;
    MolTemplate::absToRelIface = savedAbsToRelIface;
    Interface::State::totalNumOfStates = savedTotalNumOfStates;
    RxnBase::numberOfRxns = savedNumberOfRxns;
    RxnBase::totRxnSpecies = savedTotRxnSpecies;
    Molecule::numberOfMolecules = savedNumberOfMolecules;
    Complex::numberOfComplexes = savedNumberOfComplexes;
    Molecule::emptyMolList = savedEmptyMolList;
    Complex::emptyComList = savedEmptyComList;
    Parameters::lastUpdateTransition = savedLastUpdate;

    // 7. Clean up the scratch file.
    std::remove(kRRFileName);

    std::cerr << "[SETUP] parse finished (file opened = " << std::boolalpha
              << res.fileOpened << ")\n";
    return res;
}

/*! \brief Parse the file exactly once and share the result with every test. */
const RRResult& rr_result()
{
    static const RRResult result = rr_build_result();
    return result;
}

} // namespace

// -----------------------------------------------------------------------------
// Test 1: the [parameters] block.
//
// Criteria: every "keyword = value" line in the header must land in the matching
// Parameters member, in the order the parser consumes them.  simItr is also
// mirrored into params.itrRestartFrom by the routine.
// -----------------------------------------------------------------------------
void read_restart_test_parameters_block()
{
    std::cerr << "\n[TEST] read_restart_test_parameters_block\n"
              << "  Source:        src/io/read_restart.cpp\n"
              << "  Section:       parameter header (keyword = value lines)\n"
              << "  Pass criteria: each keyword value is stored in the matching\n"
              << "                 Parameters member and simItr is echoed into\n"
              << "                 params.itrRestartFrom.\n";

    const RRResult& r = rr_result();
    ASSERT_TRUE(r.fileOpened) << "the synthetic restart file could not be opened";

    // Iteration bookkeeping.
    EXPECT_EQ(r.params.nItr, 1000LL) << "nItr should be 1000";
    EXPECT_EQ(r.simItr, 250LL) << "simItr (the out-parameter) should be 250";
    EXPECT_EQ(r.params.itrRestartFrom, 250LL)
        << "itrRestartFrom must be set from the simItr line";
    EXPECT_DOUBLE_EQ(r.params.timeRestartFrom, 0.005) << "timeRestartFrom should be 0.005 s";

    // Species / complex counts.
    EXPECT_EQ(r.params.numMolTypes, 1) << "numMolTypes should be 1";
    EXPECT_EQ(r.params.numTotalSpecies, 3) << "numTotalSpecies should be 3";
    EXPECT_EQ(r.params.numTotalComplex, 2) << "numTotalComplex should be 2";
    EXPECT_EQ(r.params.numTotalUnits, 4u) << "numTotalUnits should be 4";
    EXPECT_EQ(r.params.numLipids, 0) << "numLipids should be 0";

    // Propagation / limits.
    EXPECT_DOUBLE_EQ(r.params.timeStep, 0.1) << "timeStep should be 0.1 us";
    EXPECT_EQ(r.params.max2DRxns, 5000) << "max2DRxns should be 5000";
    EXPECT_DOUBLE_EQ(r.params.overlapSepLimit, 0.25) << "overlapSepLimit should be 0.25 nm";
    EXPECT_DOUBLE_EQ(r.params.rMaxLimit, 12.5) << "rMaxLimit should be 12.5";
    EXPECT_DOUBLE_EQ(r.params.scaleMaxDisplace, 55.5) << "scaleMaxDisplace should be 55.5";

    // Output intervals / flags.
    EXPECT_EQ(r.params.timeWrite, 10LL) << "timeWrite should be 10";
    EXPECT_EQ(r.params.trajWrite, 20LL) << "trajWrite should be 20";
    EXPECT_EQ(r.params.restartWrite, 30LL) << "restartWrite should be 30";
    EXPECT_EQ(r.params.pdbWrite, 40LL) << "pdbWrite should be 40";
    EXPECT_TRUE(r.params.assocDissocWrite) << "assocDissocWrite should be true (read as 1)";
    EXPECT_EQ(r.params.checkPoint, 50LL) << "checkPoint should be 50";
    EXPECT_EQ(r.params.transitionWrite, 60LL) << "transitionWrite should be 60";
    EXPECT_TRUE(r.params.clusterOverlapCheck) << "clusterOverlapCheck should be true";

    // The two *optional* trailing keywords, handled by the getline/'=' loop.
    EXPECT_TRUE(r.params.rngwrite) << "RNGwrite = 1 should be picked up by the optional-key loop";
    EXPECT_EQ(r.params.bondedComplexWrite, 70LL)
        << "bondedComplexWrite = 70 should be picked up by the optional-key loop";

    // The line that terminates the optional-key loop holds lastUpdateTransition.
    ASSERT_EQ(r.statLastUpdateTransition.size(), 3u)
        << "three lastUpdateTransition entries were written";
    EXPECT_EQ(r.statLastUpdateTransition[0], 1LL);
    EXPECT_EQ(r.statLastUpdateTransition[1], 2LL);
    EXPECT_EQ(r.statLastUpdateTransition[2], 3LL);
}

// -----------------------------------------------------------------------------
// Test 2: the Membrane / boundary information embedded in the header.
//
// Criteria: the water box triple, the six-value "membrane info" record, the
// per-state free-lipid counts and the seven-value boundary record are all
// distributed to the correct Membrane members, and waterBox.volume is recomputed.
// -----------------------------------------------------------------------------
void read_restart_test_membrane_block()
{
    std::cerr << "\n[TEST] read_restart_test_membrane_block\n"
              << "  Source:        src/io/read_restart.cpp\n"
              << "  Section:       waterBox / membrane / boundary records\n"
              << "  Pass criteria: Membrane fields match the file and\n"
              << "                 waterBox.volume == x*y*z is recomputed.\n";

    const RRResult& r = rr_result();
    ASSERT_TRUE(r.fileOpened);

    // Water box and derived volume.
    EXPECT_DOUBLE_EQ(r.membraneObject.waterBox.x, 100.0) << "waterBox.x should be 100";
    EXPECT_DOUBLE_EQ(r.membraneObject.waterBox.y, 200.0) << "waterBox.y should be 200";
    EXPECT_DOUBLE_EQ(r.membraneObject.waterBox.z, 300.0) << "waterBox.z should be 300";
    EXPECT_DOUBLE_EQ(r.membraneObject.waterBox.volume, 100.0 * 200.0 * 300.0)
        << "volume must be recomputed as x*y*z by the parser";

    // Six-value implicit-lipid record.
    EXPECT_EQ(r.membraneObject.implicitlipidIndex, -1) << "implicitlipidIndex should be -1";
    EXPECT_EQ(r.membraneObject.nSites, 1) << "nSites should be 1";
    EXPECT_EQ(r.membraneObject.nStates, 2) << "nStates should be 2";
    EXPECT_EQ(r.membraneObject.No_free_lipids, 10) << "No_free_lipids should be 10";
    EXPECT_EQ(r.membraneObject.No_protein, 20) << "No_protein should be 20";
    EXPECT_DOUBLE_EQ(r.membraneObject.totalSA, 3000.5) << "totalSA should be 3000.5";

    // One free-lipid count per state; the vector is grown to nStates entries.
    ASSERT_EQ(r.membraneObject.numberOfFreeLipidsEachState.size(), 2u)
        << "nStates == 2 so exactly two per-state counts are read";
    EXPECT_EQ(r.membraneObject.numberOfFreeLipidsEachState[0], 5);
    EXPECT_EQ(r.membraneObject.numberOfFreeLipidsEachState[1], 6);

    // Seven-value geometry record.
    EXPECT_FALSE(r.membraneObject.implicitLipid) << "implicitLipid should be false";
    EXPECT_FALSE(r.membraneObject.TwoD) << "TwoD should be false";
    EXPECT_TRUE(r.membraneObject.isBox) << "isBox should be true";
    EXPECT_FALSE(r.membraneObject.isSphere) << "isSphere should be false";
    EXPECT_DOUBLE_EQ(r.membraneObject.sphereR, 0.0) << "sphereR should be 0";
    EXPECT_FALSE(r.membraneObject.hasCompartment) << "hasCompartment should be false";
    EXPECT_DOUBLE_EQ(r.membraneObject.compartmentR, 0.0) << "compartmentR should be 0";
}

// -----------------------------------------------------------------------------
// Test 3: the SimulVolume block is deliberately *not* read (it is commented out
// in the source), so the SimulVolume argument must come back untouched.
// -----------------------------------------------------------------------------
void read_restart_test_simulvolume_untouched()
{
    std::cerr << "\n[TEST] read_restart_test_simulvolume_untouched\n"
              << "  Source:        src/io/read_restart.cpp\n"
              << "  Section:       sub-volume partitioning (commented out)\n"
              << "  Pass criteria: simulVolume keeps its default state because the\n"
              << "                 sub-volume parsing block is disabled.\n";

    const RRResult& r = rr_result();
    ASSERT_TRUE(r.fileOpened);

    EXPECT_TRUE(r.simulVolume.subCellList.empty())
        << "no sub-volumes should be created by read_restart";
    EXPECT_EQ(r.simulVolume.numSubCells.tot, 0) << "numSubCells.tot should stay 0";
    EXPECT_EQ(r.simulVolume.numSubCells.x, 0) << "numSubCells.x should stay 0";
    EXPECT_EQ(r.simulVolume.numSubCells.y, 0) << "numSubCells.y should stay 0";
    EXPECT_EQ(r.simulVolume.numSubCells.z, 0) << "numSubCells.z should stay 0";
}

// -----------------------------------------------------------------------------
// Test 4: the MolTemplate block, including the nested Interface / State records
// and the statics that describe the template table.
// -----------------------------------------------------------------------------
void read_restart_test_moltemplate_block()
{
    std::cerr << "\n[TEST] read_restart_test_moltemplate_block\n"
              << "  Source:        src/io/read_restart.cpp\n"
              << "  Section:       MolTemplate table (1 template, 1 interface, 1 state)\n"
              << "  Pass criteria: scalar template fields, coordinates, diffusion\n"
              << "                 constants, and the nested interface/state records\n"
              << "                 are reconstructed exactly.\n";

    const RRResult& r = rr_result();
    ASSERT_TRUE(r.fileOpened);

    // Statics describing the template table.
    EXPECT_EQ(r.statNumMolTypes, 1u) << "MolTemplate::numMolTypes should be 1";
    ASSERT_EQ(r.statNumEachMolType.size(), 1u) << "one entry per molecule type";
    EXPECT_EQ(r.statNumEachMolType[0], 1) << "numEachMolType[0] should be 1";
    ASSERT_EQ(r.statAbsToRelIface.size(), 1u) << "absToRelIface has one entry";
    EXPECT_EQ(r.statAbsToRelIface[0], 0) << "absToRelIface[0] should be 0";
    EXPECT_EQ(r.statTotalNumOfStates, 1) << "Interface::State::totalNumOfStates should be 1";

    ASSERT_EQ(r.molTemplateList.size(), 1u) << "exactly one MolTemplate is in the file";
    const MolTemplate& t = r.molTemplateList[0];

    // Scalar identity / physical fields.
    EXPECT_EQ(t.molTypeIndex, 0) << "molTypeIndex should be 0";
    EXPECT_EQ(t.molName, "A") << "molName should be \"A\"";
    EXPECT_EQ(t.copies, 5) << "copies should be 5";
    EXPECT_DOUBLE_EQ(t.mass, 100.5) << "mass should be 100.5";
    EXPECT_DOUBLE_EQ(t.radius, 2.5) << "radius should be 2.5";

    // Boolean / integer flag row.
    EXPECT_FALSE(t.isLipid) << "isLipid should be false";
    EXPECT_FALSE(t.isImplicitLipid) << "isImplicitLipid should be false";
    EXPECT_FALSE(t.isRod) << "isRod should be false";
    EXPECT_FALSE(t.isPoint) << "isPoint should be false";
    EXPECT_TRUE(t.checkOverlap) << "checkOverlap should be true (read as 1)";
    EXPECT_FALSE(t.countTransition) << "countTransition should be false";
    EXPECT_EQ(t.transitionMatrixSize, 500) << "transitionMatrixSize should be 500";
    EXPECT_FALSE(t.outsideCompartment) << "outsideCompartment should be false";
    EXPECT_FALSE(t.insideCompartment) << "insideCompartment should be false";
    EXPECT_FALSE(t.crossesCompartment) << "crossesCompartment should be false";
    EXPECT_EQ(t.transmissionRxnIndex, -1) << "transmissionRxnIndex should be -1";

    // Because countTransition is false the lifetime / transition matrices are skipped.
    EXPECT_TRUE(t.lifeTime.empty()) << "lifeTime must stay empty when countTransition is false";
    EXPECT_TRUE(t.transitionMatrix.empty())
        << "transitionMatrix must stay empty when countTransition is false";

    // Coordinates and diffusion constants.
    EXPECT_DOUBLE_EQ(t.comCoord.x, 0.0);
    EXPECT_DOUBLE_EQ(t.comCoord.y, 0.0);
    EXPECT_DOUBLE_EQ(t.comCoord.z, 0.0);
    EXPECT_DOUBLE_EQ(t.D.x, 10.0) << "D.x should be 10";
    EXPECT_DOUBLE_EQ(t.D.y, 10.0) << "D.y should be 10";
    EXPECT_DOUBLE_EQ(t.D.z, 10.0) << "D.z should be 10";
    EXPECT_DOUBLE_EQ(t.Dr.x, 0.5) << "Dr.x should be 0.5";
    EXPECT_DOUBLE_EQ(t.Dr.y, 0.5) << "Dr.y should be 0.5";
    EXPECT_DOUBLE_EQ(t.Dr.z, 0.5) << "Dr.z should be 0.5";

    // Optional lists were written with size zero.
    EXPECT_TRUE(t.rxnPartners.empty()) << "rxnPartners size was 0 in the file";
    EXPECT_TRUE(t.bondList.empty()) << "bondList size was 0 in the file";
    EXPECT_TRUE(t.ifacesWithStates.empty()) << "ifacesWithStates size was 0 in the file";
    EXPECT_TRUE(t.monomerList.empty()) << "monomerList size was 0 in the file";

    // The single interface and its single state.
    ASSERT_EQ(t.interfaceList.size(), 1u) << "one interface was written";
    const Interface& iface = t.interfaceList[0];
    EXPECT_EQ(iface.index, 0) << "interface relative index should be 0";
    EXPECT_EQ(iface.name, "a") << "interface name should be \"a\"";
    EXPECT_DOUBLE_EQ(iface.iCoord.x, 1.0) << "interface iCoord.x should be 1.0";
    EXPECT_DOUBLE_EQ(iface.iCoord.y, 0.0);
    EXPECT_DOUBLE_EQ(iface.iCoord.z, 0.0);

    ASSERT_EQ(iface.stateList.size(), 1u) << "one state was written";
    const Interface::State& state = iface.stateList[0];
    EXPECT_EQ(state.index, 0) << "state absolute index should be 0";
    EXPECT_EQ(state.iden, 'U') << "state identity character should be 'U'";
    EXPECT_TRUE(state.rxnPartners.empty()) << "rxnPartners size was 0";
    ASSERT_EQ(state.myForwardRxns.size(), 1u) << "one forward reaction was listed";
    EXPECT_EQ(state.myForwardRxns[0], 0u) << "the listed forward reaction index is 0";
    EXPECT_TRUE(state.myCreateDestructRxns.empty()) << "no create/destruct reactions listed";
    EXPECT_TRUE(state.stateChangeRxns.empty()) << "no state change reactions listed";
}

// -----------------------------------------------------------------------------
// Test 5: the reaction block - one bimolecular ForwardRxn plus its BackRxn, and
// zero create/destruct and transmission reactions.
// -----------------------------------------------------------------------------
void read_restart_test_reaction_block()
{
    std::cerr << "\n[TEST] read_restart_test_reaction_block\n"
              << "  Source:        src/io/read_restart.cpp\n"
              << "  Section:       reactions (1 forward, 1 back, 0 create/destruct, 0 transmission)\n"
              << "  Pass criteria: reaction bookkeeping, association geometry (including\n"
              << "                 the \"nan\" angle fields), reactant/product interface\n"
              << "                 records and the rate list are all restored.\n";

    const RRResult& r = rr_result();
    ASSERT_TRUE(r.fileOpened);

    // Reaction table statics and container sizes.
    EXPECT_EQ(r.statNumberOfRxns, 2u) << "RxnBase::numberOfRxns should be 2";
    EXPECT_EQ(r.statTotRxnSpecies, 3) << "RxnBase::totRxnSpecies should be 3";
    ASSERT_EQ(r.forwardRxns.size(), 1u) << "one forward reaction in the file";
    ASSERT_EQ(r.backRxns.size(), 1u) << "one back reaction in the file";
    EXPECT_TRUE(r.createDestructRxns.empty()) << "no create/destruct reactions in the file";
    EXPECT_TRUE(r.transmissionRxns.empty()) << "no transmission reactions in the file";

    // ---- forward reaction ----
    const ForwardRxn& fwd = r.forwardRxns[0];
    EXPECT_EQ(fwd.absRxnIndex, 0) << "absRxnIndex should be 0";
    EXPECT_EQ(fwd.relRxnIndex, 0) << "relRxnIndex should be 0";
    EXPECT_EQ(fwd.rxnLabel, "rxnA") << "rxnLabel should be \"rxnA\"";
    EXPECT_TRUE(fwd.rxnType == ReactionType::bimolecular)
        << "integer reaction type 1 maps to ReactionType::bimolecular";
    EXPECT_FALSE(fwd.isSymmetric) << "isSymmetric should be false";
    EXPECT_TRUE(fwd.isOnMem) << "isOnMem should be true";
    EXPECT_FALSE(fwd.hasStateChange) << "hasStateChange should be false";
    EXPECT_FALSE(fwd.isObserved) << "isObserved should be false";
    EXPECT_EQ(fwd.productName, "A(a!1).A(a!1)") << "productName should round-trip";
    EXPECT_TRUE(fwd.isReversible) << "isReversible should be true";
    EXPECT_EQ(fwd.conjBackRxnIndex, 0) << "conjBackRxnIndex should be 0";
    EXPECT_FALSE(fwd.irrevRingClosure) << "irrevRingClosure should be false";
    EXPECT_DOUBLE_EQ(fwd.bindRadSameCom, 1.1) << "bindRadSameCom should be 1.1";
    EXPECT_DOUBLE_EQ(fwd.loopCoopFactor, 1.0) << "loopCoopFactor should be 1.0";
    EXPECT_DOUBLE_EQ(fwd.length3Dto2D, -1.0) << "length3Dto2D should be -1";
    EXPECT_DOUBLE_EQ(fwd.area3Dto1D, -1.0) << "area3Dto1D should be -1";
    EXPECT_FALSE(fwd.excludeVolumeBound) << "excludeVolumeBound should be false";
    EXPECT_FALSE(fwd.isCoupled) << "isCoupled should be false (no coupled record follows)";

    // Association geometry: numeric angles parse normally, "nan" tokens become NaN.
    EXPECT_DOUBLE_EQ(fwd.bindRadius, 1.5) << "bindRadius should be 1.5 nm";
    EXPECT_DOUBLE_EQ(fwd.assocAngles.theta1, 1.5708) << "theta1 should be 1.5708";
    EXPECT_DOUBLE_EQ(fwd.assocAngles.theta2, 3.14159) << "theta2 should be 3.14159";
    EXPECT_TRUE(std::isnan(fwd.assocAngles.phi1)) << "phi1 written as \"nan\" should be NaN";
    EXPECT_TRUE(std::isnan(fwd.assocAngles.phi2)) << "phi2 written as \"nan\" should be NaN";
    EXPECT_TRUE(std::isnan(fwd.assocAngles.omega)) << "omega written as \"nan\" should be NaN";

    // Norm vectors.
    EXPECT_DOUBLE_EQ(fwd.norm1.x, 0.0);
    EXPECT_DOUBLE_EQ(fwd.norm1.y, 0.0);
    EXPECT_DOUBLE_EQ(fwd.norm1.z, 1.0) << "norm1 should be the z unit vector";
    EXPECT_DOUBLE_EQ(fwd.norm2.z, 1.0) << "norm2 should be the z unit vector";

    // Integer reactant / product index lists.
    ASSERT_EQ(fwd.intReactantList.size(), 2u) << "two integer reactants";
    EXPECT_EQ(fwd.intReactantList[0], 0);
    EXPECT_EQ(fwd.intReactantList[1], 0);
    ASSERT_EQ(fwd.intProductList.size(), 1u) << "one integer product";
    EXPECT_EQ(fwd.intProductList[0], 2);

    // Reactant interface records (free interfaces, state 'X').
    ASSERT_EQ(fwd.reactantListNew.size(), 2u) << "two reactant interfaces";
    for (std::size_t i = 0; i < fwd.reactantListNew.size(); ++i) {
        const RxnIface& ri = fwd.reactantListNew[i];
        EXPECT_EQ(ri.molTypeIndex, 0) << "reactant " << i << " molTypeIndex";
        EXPECT_EQ(ri.ifaceName, "a") << "reactant " << i << " ifaceName";
        EXPECT_EQ(ri.absIfaceIndex, 0) << "reactant " << i << " absIfaceIndex";
        EXPECT_EQ(ri.relIfaceIndex, 0) << "reactant " << i << " relIfaceIndex";
        EXPECT_EQ(ri.requiresState, 'X') << "reactant " << i << " requiresState";
        EXPECT_FALSE(ri.requiresInteraction) << "reactant " << i << " must be free";
    }

    // Product interface records (bound interfaces, state 'Y').
    ASSERT_EQ(fwd.productListNew.size(), 2u) << "two product interfaces";
    for (std::size_t i = 0; i < fwd.productListNew.size(); ++i) {
        const RxnIface& pi = fwd.productListNew[i];
        EXPECT_EQ(pi.absIfaceIndex, 2) << "product " << i << " absIfaceIndex";
        EXPECT_EQ(pi.requiresState, 'Y') << "product " << i << " requiresState";
        EXPECT_TRUE(pi.requiresInteraction) << "product " << i << " must be bound";
    }

    // Rate list (no ancillary interface lists were written).
    ASSERT_EQ(fwd.rateList.size(), 1u) << "one rate entry";
    EXPECT_DOUBLE_EQ(fwd.rateList[0].rate, 10.5) << "forward rate should be 10.5";
    EXPECT_TRUE(fwd.rateList[0].otherIfaceLists.empty())
        << "otherIfaceLists size was written as 0";

    // ---- back reaction ----
    const BackRxn& back = r.backRxns[0];
    EXPECT_EQ(back.absRxnIndex, 1) << "back reaction absRxnIndex should be 1";
    EXPECT_EQ(back.relRxnIndex, 0) << "back reaction relRxnIndex should be 0";
    EXPECT_TRUE(back.rxnType == ReactionType::bimolecular)
        << "back reaction type should also be bimolecular";
    EXPECT_TRUE(back.isOnMem) << "back reaction isOnMem should be true";
    EXPECT_FALSE(back.isObserved) << "back reaction isObserved should be false";
    EXPECT_EQ(back.conjForwardRxnIndex, 0u) << "conjForwardRxnIndex should be 0";
    EXPECT_FALSE(back.isCoupled) << "back reaction isCoupled should be false";

    // For the back reaction reactants and products are swapped relative to fwd.
    ASSERT_EQ(back.intReactantList.size(), 1u) << "one integer reactant";
    EXPECT_EQ(back.intReactantList[0], 2);
    ASSERT_EQ(back.intProductList.size(), 2u) << "two integer products";
    EXPECT_EQ(back.intProductList[0], 0);
    EXPECT_EQ(back.intProductList[1], 0);

    ASSERT_EQ(back.reactantListNew.size(), 2u) << "two reactant interfaces";
    EXPECT_TRUE(back.reactantListNew[0].requiresInteraction)
        << "back-reaction reactants are the bound product interfaces";
    EXPECT_EQ(back.reactantListNew[0].requiresState, 'Y');
    ASSERT_EQ(back.productListNew.size(), 2u) << "two product interfaces";
    EXPECT_FALSE(back.productListNew[0].requiresInteraction)
        << "back-reaction products are the free interfaces";
    EXPECT_EQ(back.productListNew[0].requiresState, 'X');

    ASSERT_EQ(back.rateList.size(), 1u) << "one rate entry";
    EXPECT_DOUBLE_EQ(back.rateList[0].rate, 0.5) << "back rate should be 0.5";
}

// -----------------------------------------------------------------------------
// Test 6: the Molecule block, including the free/bound interface bookkeeping and
// the "bound interface has an extra interaction line" branch.
// -----------------------------------------------------------------------------
void read_restart_test_molecule_block()
{
    std::cerr << "\n[TEST] read_restart_test_molecule_block\n"
              << "  Source:        src/io/read_restart.cpp\n"
              << "  Section:       molecule coordinates (2 molecules)\n"
              << "  Pass criteria: scalar molecule fields, coordinates, free/bound\n"
              << "                 lists and the extra Interaction record that only\n"
              << "                 follows a bound interface are all restored.\n";

    const RRResult& r = rr_result();
    ASSERT_TRUE(r.fileOpened);

    EXPECT_EQ(r.statNumberOfMolecules, 2) << "Molecule::numberOfMolecules should be 2";
    EXPECT_TRUE(r.statEmptyMolList.empty()) << "emptyMolList size was written as 0";
    ASSERT_EQ(r.moleculeList.size(), 2u) << "two molecules in the file";

    // ---- molecule 0: entirely free ----
    const Molecule& m0 = r.moleculeList[0];
    EXPECT_EQ(m0.index, 0) << "molecule 0 index";
    EXPECT_FALSE(m0.isEmpty) << "molecule 0 should not be empty";
    EXPECT_EQ(m0.myComIndex, 0) << "molecule 0 parent complex index";
    EXPECT_EQ(m0.molTypeIndex, 0) << "molecule 0 molTypeIndex";
    EXPECT_EQ(m0.mySubVolIndex, 5) << "molecule 0 mySubVolIndex";
    EXPECT_DOUBLE_EQ(m0.mass, 100.5) << "molecule 0 mass";
    EXPECT_FALSE(m0.isLipid) << "molecule 0 isLipid";
    EXPECT_FALSE(m0.isImplicitLipid) << "molecule 0 isImplicitLipid";
    EXPECT_EQ(m0.linksToSurface, 0) << "molecule 0 linksToSurface";
    EXPECT_FALSE(m0.isPromoter) << "molecule 0 isPromoter";
    EXPECT_DOUBLE_EQ(m0.comCoord.x, 1.0);
    EXPECT_DOUBLE_EQ(m0.comCoord.y, 2.0);
    EXPECT_DOUBLE_EQ(m0.comCoord.z, 3.0);

    ASSERT_EQ(m0.freelist.size(), 1u) << "molecule 0 has one free interface listed";
    EXPECT_EQ(m0.freelist[0], 0);
    EXPECT_TRUE(m0.bndlist.empty()) << "molecule 0 has no bound interfaces listed";
    EXPECT_TRUE(m0.bndpartner.empty()) << "molecule 0 has no bound partners listed";

    ASSERT_EQ(m0.interfaceList.size(), 1u) << "molecule 0 has one interface";
    const Molecule::Iface& i0 = m0.interfaceList[0];
    EXPECT_EQ(i0.index, 0) << "interface absolute index";
    EXPECT_EQ(i0.relIndex, 0) << "interface relative index";
    EXPECT_EQ(i0.molTypeIndex, 0) << "interface molTypeIndex";
    EXPECT_EQ(i0.stateIndex, 0) << "interface stateIndex";
    EXPECT_EQ(i0.stateIden, 'U') << "interface state identity";
    EXPECT_FALSE(i0.isBound) << "molecule 0's interface is free";
    EXPECT_DOUBLE_EQ(i0.coord.x, 1.5);
    EXPECT_DOUBLE_EQ(i0.coord.y, 2.0);
    EXPECT_DOUBLE_EQ(i0.coord.z, 3.0);
    // A free interface has no Interaction record, so the defaults survive.
    EXPECT_EQ(i0.interaction.partnerIndex, -1)
        << "no interaction line is read for a free interface";

    // Reweighting histories were all written with size 0.
    EXPECT_TRUE(m0.prevlist.empty());
    EXPECT_TRUE(m0.prevmyface.empty());
    EXPECT_TRUE(m0.prevpface.empty());
    EXPECT_TRUE(m0.prevnorm.empty());
    EXPECT_TRUE(m0.ps_prev.empty());
    EXPECT_TRUE(m0.prevsep.empty());

    // ---- molecule 1: bound to molecule 0 ----
    const Molecule& m1 = r.moleculeList[1];
    EXPECT_EQ(m1.index, 1) << "molecule 1 index";
    EXPECT_EQ(m1.myComIndex, 1) << "molecule 1 parent complex index";
    EXPECT_EQ(m1.mySubVolIndex, 6) << "molecule 1 mySubVolIndex";
    EXPECT_EQ(m1.linksToSurface, 1) << "molecule 1 linksToSurface should be 1";
    EXPECT_DOUBLE_EQ(m1.comCoord.x, -1.0);
    EXPECT_DOUBLE_EQ(m1.comCoord.y, -2.0);
    EXPECT_DOUBLE_EQ(m1.comCoord.z, -3.0);

    EXPECT_TRUE(m1.freelist.empty()) << "molecule 1 has no free interfaces listed";
    ASSERT_EQ(m1.bndlist.size(), 1u) << "molecule 1 has one bound interface listed";
    EXPECT_EQ(m1.bndlist[0], 0);
    ASSERT_EQ(m1.bndpartner.size(), 1u) << "molecule 1 has one bound partner listed";
    EXPECT_EQ(m1.bndpartner[0], 0);

    ASSERT_EQ(m1.interfaceList.size(), 1u) << "molecule 1 has one interface";
    const Molecule::Iface& i1 = m1.interfaceList[0];
    EXPECT_TRUE(i1.isBound) << "molecule 1's interface is bound";
    EXPECT_DOUBLE_EQ(i1.coord.x, -1.5);
    // Because isBound is true an extra Interaction line is consumed.
    EXPECT_EQ(i1.interaction.partnerIndex, 0) << "interaction partnerIndex should be 0";
    EXPECT_EQ(i1.interaction.partnerIfaceIndex, 0)
        << "interaction partnerIfaceIndex should be 0";
    EXPECT_EQ(i1.interaction.conjBackRxn, 0) << "interaction conjBackRxn should be 0";
}

// -----------------------------------------------------------------------------
// Test 7: the Complex block.
// -----------------------------------------------------------------------------
void read_restart_test_complex_block()
{
    std::cerr << "\n[TEST] read_restart_test_complex_block\n"
              << "  Source:        src/io/read_restart.cpp\n"
              << "  Section:       complexes (2 complexes)\n"
              << "  Pass criteria: geometry, diffusion constants, surface flags and\n"
              << "                 the three per-complex member lists are restored.\n";

    const RRResult& r = rr_result();
    ASSERT_TRUE(r.fileOpened);

    EXPECT_EQ(r.statNumberOfComplexes, 2) << "Complex::numberOfComplexes should be 2";
    EXPECT_TRUE(r.statEmptyComList.empty()) << "emptyComList size was written as 0";
    ASSERT_EQ(r.complexList.size(), 2u) << "two complexes in the file";

    // ---- complex 0: in solution ----
    const Complex& c0 = r.complexList[0];
    EXPECT_EQ(c0.index, 0) << "complex 0 index";
    EXPECT_FALSE(c0.isEmpty) << "complex 0 should not be empty";
    EXPECT_DOUBLE_EQ(c0.radius, 2.5) << "complex 0 radius";
    EXPECT_DOUBLE_EQ(c0.mass, 100.5) << "complex 0 mass";
    EXPECT_EQ(c0.linksToSurface, 0) << "complex 0 linksToSurface";
    EXPECT_EQ(c0.iLipidIndex, 0) << "complex 0 iLipidIndex";
    EXPECT_FALSE(c0.OnSurface) << "complex 0 OnSurface";
    EXPECT_FALSE(c0.onFiber) << "complex 0 onFiber";
    EXPECT_DOUBLE_EQ(c0.comCoord.x, 1.0);
    EXPECT_DOUBLE_EQ(c0.comCoord.y, 2.0);
    EXPECT_DOUBLE_EQ(c0.comCoord.z, 3.0);
    EXPECT_DOUBLE_EQ(c0.D.x, 10.0) << "complex 0 D.x";
    EXPECT_DOUBLE_EQ(c0.D.z, 10.0) << "complex 0 D.z";
    EXPECT_DOUBLE_EQ(c0.Dr.x, 0.5) << "complex 0 Dr.x";

    ASSERT_EQ(c0.memberList.size(), 1u) << "complex 0 has one member molecule";
    EXPECT_EQ(c0.memberList[0], 0) << "complex 0 owns molecule 0";
    ASSERT_EQ(c0.numEachMol.size(), 1u) << "complex 0 numEachMol has one entry";
    EXPECT_EQ(c0.numEachMol[0], 1) << "complex 0 contains one molecule of type 0";
    ASSERT_EQ(c0.lastNumberUpdateItrEachMol.size(), 1u)
        << "complex 0 lastNumberUpdateItrEachMol has one entry";
    EXPECT_EQ(c0.lastNumberUpdateItrEachMol[0], 0LL);

    // ---- complex 1: attached to the surface ----
    const Complex& c1 = r.complexList[1];
    EXPECT_EQ(c1.index, 1) << "complex 1 index";
    EXPECT_DOUBLE_EQ(c1.radius, 3.5) << "complex 1 radius";
    EXPECT_EQ(c1.linksToSurface, 1) << "complex 1 linksToSurface should be 1";
    EXPECT_TRUE(c1.OnSurface) << "complex 1 OnSurface should be true";
    EXPECT_FALSE(c1.onFiber) << "complex 1 onFiber should be false";
    EXPECT_DOUBLE_EQ(c1.comCoord.x, -1.0);
    EXPECT_DOUBLE_EQ(c1.D.z, 0.0) << "complex 1 has no z-diffusion (membrane bound)";
    EXPECT_DOUBLE_EQ(c1.Dr.z, 0.0) << "complex 1 has no z-rotation (membrane bound)";
    ASSERT_EQ(c1.memberList.size(), 1u) << "complex 1 has one member molecule";
    EXPECT_EQ(c1.memberList[0], 1) << "complex 1 owns molecule 1";
}

// -----------------------------------------------------------------------------
// Test 8: the observables map and the copyCounters block (scalar counters, the
// three event histograms and the per-species bindPairList).
// -----------------------------------------------------------------------------
void read_restart_test_observables_and_counters()
{
    std::cerr << "\n[TEST] read_restart_test_observables_and_counters\n"
              << "  Source:        src/io/read_restart.cpp\n"
              << "  Section:       observables map + copyCounters\n"
              << "  Pass criteria: the observable name/count pair is inserted into\n"
              << "                 the map, the nine scalar counters are restored,\n"
              << "                 all three event histograms are filled, and the\n"
              << "                 per-species bindPairList rows are rebuilt.\n";

    const RRResult& r = rr_result();
    ASSERT_TRUE(r.fileOpened);

    // Observables.
    ASSERT_EQ(r.observablesList.size(), 1u) << "one observable was written";
    auto obs = r.observablesList.find("obsA");
    ASSERT_NE(obs, r.observablesList.end()) << "observable \"obsA\" should be present";
    EXPECT_EQ(obs->second, 7) << "observable \"obsA\" count should be 7";

    // Scalar counters.
    EXPECT_EQ(r.counterArrays.nLoops, 3) << "nLoops should be 3";
    EXPECT_EQ(r.counterArrays.nCancelOverlapPartner, 1) << "nCancelOverlapPartner should be 1";
    EXPECT_EQ(r.counterArrays.nCancelOverlapSystem, 2) << "nCancelOverlapSystem should be 2";
    EXPECT_EQ(r.counterArrays.nCancelDisplace2D, 4) << "nCancelDisplace2D should be 4";
    EXPECT_EQ(r.counterArrays.nCancelDisplace3D, 5) << "nCancelDisplace3D should be 5";
    EXPECT_EQ(r.counterArrays.nCancelDisplace3Dto2D, 6)
        << "nCancelDisplace3Dto2D should be 6";
    EXPECT_EQ(r.counterArrays.nCancelSpanBox, 7) << "nCancelSpanBox should be 7";
    EXPECT_EQ(r.counterArrays.nAssocSuccess, 8) << "nAssocSuccess should be 8";
    EXPECT_EQ(r.counterArrays.eventArraySize, kRREventArraySize)
        << "eventArraySize should be " << kRREventArraySize;

    // Event histograms: the file holds 1s, 2s and 3s respectively.
    ASSERT_EQ(static_cast<int>(r.counterArrays.events3D.size()), kRREventArraySize);
    ASSERT_EQ(static_cast<int>(r.counterArrays.events3Dto2D.size()), kRREventArraySize);
    ASSERT_EQ(static_cast<int>(r.counterArrays.events2D.size()), kRREventArraySize);
    for (int i = 0; i < kRREventArraySize; ++i) {
        EXPECT_EQ(r.counterArrays.events3D[i], 1) << "events3D[" << i << "] should be 1";
        EXPECT_EQ(r.counterArrays.events3Dto2D[i], 2)
            << "events3Dto2D[" << i << "] should be 2";
        EXPECT_EQ(r.counterArrays.events2D[i], 3) << "events2D[" << i << "] should be 3";
    }

    // Per-species dissociation pools.
    ASSERT_EQ(r.counterArrays.bindPairList.size(), 2u) << "two species were written";
    ASSERT_EQ(r.counterArrays.bindPairList[0].size(), 1u)
        << "species 0 has a single bind-pair entry";
    EXPECT_EQ(r.counterArrays.bindPairList[0][0], 0) << "species 0 entry should be 0";
    ASSERT_EQ(r.counterArrays.bindPairList[1].size(), 2u)
        << "species 1 has two bind-pair entries";
    EXPECT_EQ(r.counterArrays.bindPairList[1][0], 1) << "species 1 first entry should be 1";
    EXPECT_EQ(r.counterArrays.bindPairList[1][1], 3) << "species 1 second entry should be 3";
}

// -----------------------------------------------------------------------------
// GoogleTest wrappers.  Each named test_* helper is invoked from its own TEST so
// a failure in one section does not hide the others.
// -----------------------------------------------------------------------------
TEST(ReadRestart, ParametersBlock) { read_restart_test_parameters_block(); }
TEST(ReadRestart, MembraneBlock) { read_restart_test_membrane_block(); }
TEST(ReadRestart, SimulVolumeUntouched) { read_restart_test_simulvolume_untouched(); }
TEST(ReadRestart, MolTemplateBlock) { read_restart_test_moltemplate_block(); }
TEST(ReadRestart, ReactionBlock) { read_restart_test_reaction_block(); }
TEST(ReadRestart, MoleculeBlock) { read_restart_test_molecule_block(); }
TEST(ReadRestart, ComplexBlock) { read_restart_test_complex_block(); }
TEST(ReadRestart, ObservablesAndCounters) { read_restart_test_observables_and_counters(); }